#remote-theme: andrewhwanpark/dark-poole
title: Octocat's homepage
description: Personal site of Juan Rizo
author: Juan Rizo
location: Perú 🇵🇪
paginate: 20
subscribe: false

remote_theme: ngzhio/jekyll-theme-hamilton
skin: midnight

# SEO Tag (Optional)
twitter:
  username: Milhouse_Van_Ho
  card: summary
logo: avatar.jpg
social:
  name: Juan Riso Name
  links:
    - https://twitter.com/Milhouse_Van_Ho
    - https://github.com/ngzhio
lang: en

plugins:
  - jekyll-remote-theme

