#remote-theme: andrewhwanpark/dark-poole
title: Juan Rizo blog
description: Personal site of Juan Rizo
author: Juan Rizo
location: Lima, Peru 🇵🇪
email: ngzhio@gmail.com
paginate: 20
subscribe: false
avatar: /avatar.jpg


#remote_theme: ngzhio/jekyll-theme-hamilton
#skin: midnight
remote_theme: andrewhwanpark/dark-poole

include:
  - _pages
  
defaults:
  - scope:
    path: ""      
    type: "posts"

# SEO Tag (Optional)
twitter:
  username: Milhouse_Van_Ho
  card: summary
  logo: avatar.jpg
social:
  name: Juan Riso Name
  links:
    - https://twitter.com/Milhouse_Van_Ho
    - https://github.com/ngzhio
lang: en

plugins:
  - jekyll-remote-theme

