#remote-theme: andrewhwanpark/dark-poole
title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!
author: Juan Rizo
location: Perú 🇵🇪
paginate: 20
subscribe: false

remote_theme: ngzhio/jekyll-theme-hamilton
skin: midnight

plugins:
  - jekyll-remote-theme

